// Sample data for the HomeMux iOS UI kit (from MVP-PLAN §15.2 home-screen layout).
window.HMX_HOSTS = [
  {
    id: "mac",
    title: "Mac mini",
    endpoint: "alex@mac-mini.local",
    port: 22,
    transport: "Automatic",
    activeTransport: "Mosh",
    auth: "Private Key",
    startup: "Plain shell",
    startupIcon: "square-terminal",
    theme: "homemux-dark",
  },
  {
    id: "claude",
    title: "Mac mini · claude",
    endpoint: "alex@mac-mini.local",
    port: 22,
    transport: "Automatic",
    activeTransport: "Mosh",
    auth: "Private Key",
    startup: "tmux · claude",
    startupIcon: "layers",
    theme: "homemux-dark",
  },
  {
    id: "codex",
    title: "Mac mini · codex",
    endpoint: "alex@mac-mini.local",
    port: 22,
    transport: "Automatic",
    activeTransport: "Mosh",
    auth: "Private Key",
    startup: "tmux · codex",
    startupIcon: "layers",
    theme: "ember-console",
  },
  {
    id: "vps",
    title: "VPS",
    endpoint: "root@example.com",
    port: 22,
    transport: "SSH",
    activeTransport: "SSH",
    auth: "Password",
    startup: "Plain shell",
    startupIcon: "square-terminal",
    theme: "homemux-dark",
  },
];
